"""add evaluations table

Revision ID: 666fd1a8412d
Revises: b7c8d9e0f1a2
Create Date: 2026-03-09 15:36:02.094135

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "666fd1a8412d"
down_revision: str | Sequence[str] | None = "b7c8d9e0f1a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_position_id", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("rubric_version_id", sa.Integer(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("execution_arn", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_position_id"],
            ["candidate_positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rubric_version_id"],
            ["position_rubric_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_position_id", "step_type", "version"),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evaluations_candidate_position_id"),
            ["candidate_position_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_evaluations_candidate_position_status",
            ["candidate_position_id", "status"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index("ix_evaluations_candidate_position_status")
        batch_op.drop_index(batch_op.f("ix_evaluations_candidate_position_id"))

    op.drop_table("evaluations")
    # ### end Alembic commands ###
